version: "3"
services: 

  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5433:5432

  sales-db:
    image: tutum/mongodb
    container_name: sales-db
    restart: always
    environment:
      - MONGODB_USER=admin
      - MONGODB_DATABASE=sales-db
      - MONGODB_PASS=1234
    ports:
      - 28017:28017
      - 27017:27017

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    restart: always
    environment:
      - MONGODB_USER=admin
      - MONGODB_DATABASE=sales-db
      - MONGODB_PASS=1234
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672