INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Comic Books');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Movies');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Books');

INSERT INTO SUPPLIER (NAME) VALUES ('Panini Comics');
INSERT INTO SUPPLIER (NAME) VALUES ('Amazon');

INSERT INTO PRODUCT (NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES ('Crise nas Infinitas Terras', 1, 1, 10, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES ('Interestelar', 2, 2, 5, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES ('Técnicas de Invasão', 2, 3, 3, CURRENT_TIMESTAMP);
